
post http://localhost:4444/companyadmin/saveadmin
Content-Type: application/json

{
    "username":"praveen",
    "email":"praveen@gmail.com",
    "password":"praveen123"
}


###
get http://localhost:4444/companyadmin